export const LYRICS_LIST_TOOGLE = "LYRICS_LIST_TOOGLE";

export const LYRICS_DATA_FOUND = "LYRICS_DATA_FOUND";
export const LYRICS_DATA_NOT_FOUND = "LYRICS_DATA_NOT_FOUND";

export const UPDATE_SEARCH_RESULT = "UPDATE_SEARCH_RESULT";
export const REMOVE_SEARCH_RESULT = "REMOVE_SEARCH_RESULT";

export const UPDATE_SEARCHED_VALUE = "UPDATE_SEARCHED_VALUE";
export const REMOVE_SEARCHED_VALUE = "REMOVE_SEARCHED_VALUE";

export const COUNTER_TOGGLE = "COUNTER_TOGGLE";

export const COUNTER_ITERATION = "COUNTER_ITERATION";
export const COUNTER_CLEAR_ITERATION = "COUNTER_CLEAR_ITERATION";

export const COUNTER_SET_SCROLL_DELAY = "COUNTER_SET_SCROLL_DELAY";

export const COUNTER_SET_SONG_TIMING = "COUNTER_SET_SONG_TIMING";
